const bikes = [
  {
    id: 1,
    name: "Royal Enfield Classic 350",
    img: "https://images.app.goo.gl/vtqucLCsQRxf849C6",
    rent_per_day: 1200,
    description: "Classic design with powerful performance for long rides.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Stealth Black",
      seating_capacity: 2,
    },
  },
  {
    id: 2,
    name: "Bajaj Pulsar 220F",
    img: "https://images.app.goo.gl/bTmjDomipVJdi1Dn6",
    rent_per_day: 900,
    description: "Sporty and reliable bike suitable for city and highways.",
    details: {
      model_year: 2021,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Red",
      seating_capacity: 2,
    },
  },
  {
    id: 3,
    name: "KTM Duke 200",
    img: "https://images.app.goo.gl/rYnwBmgtgfiw2AKb8",
    rent_per_day: 1300,
    description: "Lightweight street bike with high performance engine.",
    details: {
      model_year: 2023,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Orange",
      seating_capacity: 2,
    },
  },
  {
    id: 4,
    name: "Yamaha FZ-S V3",
    img: "https://images.app.goo.gl/zniEP3rNiNZEXXpj9",
    rent_per_day: 950,
    description: "Comfortable and efficient with premium looks.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Matte Blue",
      seating_capacity: 2,
    },
  },
  {
    id: 5,
    name: "TVS Apache RTR 160",
    img: "https://images.app.goo.gl/UNrKoy2rD8C5Pfor7",
    rent_per_day: 850,
    description: "Responsive handling with a stylish body frame.",
    details: {
      model_year: 2021,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "White",
      seating_capacity: 2,
    },
  },
  {
    id: 6,
    name: "Honda Activa 6G",
    img: "https://images.app.goo.gl/XZmU7rcRc12mSHdM8",
    rent_per_day: 600,
    description: "India’s favorite scooter with great mileage and comfort.",
    details: {
      model_year: 2023,
      fuel_type: "Petrol",
      transmission: "Automatic",
      color: "Grey",
      seating_capacity: 2,
    },
  },
  {
    id: 7,
    name: "Suzuki Access 125",
    img: "https://images.app.goo.gl/s1FpukgXKHG8bdwG9",
    rent_per_day: 620,
    description: "Smooth and stylish ride for daily commutes.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Automatic",
      color: "Silver",
      seating_capacity: 2,
    },
  },
  {
    id: 8,
    name: "Yamaha R15 V4",
    img: "https://images.app.goo.gl/k58z1LgaX7poesNw7",
    rent_per_day: 1400,
    description: "A sporty and aggressive ride for thrill seekers.",
    details: {
      model_year: 2023,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Racing Blue",
      seating_capacity: 2,
    },
  },
  {
    id: 9,
    name: "Royal Enfield Meteor 350",
    img: "https://images.app.goo.gl/PsY5sH9maNEAv8kE6",
    rent_per_day: 1250,
    description: "Tour-ready cruiser with modern tech.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Fireball Yellow",
      seating_capacity: 2,
    },
  },
  {
    id: 10,
    name: "Hero Splendor Plus",
    img: "https://images.app.goo.gl/Zbv75zUMaEPMBM7H9",
    rent_per_day: 550,
    description: "Fuel-efficient and reliable workhorse for daily rides.",
    details: {
      model_year: 2020,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Black with Silver",
      seating_capacity: 2,
    },
  },
  {
    id: 11,
    name: "Honda CB350 H'Ness",
    img: "https://images.app.goo.gl/tTsHuQCMPvB8Txpx8",
    rent_per_day: 1100,
    description: "Retro-styled modern classic with refined power.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Pearl Nightstar Black",
      seating_capacity: 2,
    },
  },
  {
    id: 12,
    name: "Kawasaki Ninja 300",
    img: "https://images.app.goo.gl/pi8i92eGUXrPJ6x1A",
    rent_per_day: 2000,
    description: "High-performance sportbike for adventure riders.",
    details: {
      model_year: 2023,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Lime Green",
      seating_capacity: 2,
    },
  },
  {
    id: 13,
    name: "Bajaj Avenger Cruise 220",
    img: "https://images.app.goo.gl/j63YR9XfPkmrPtCZ8",
    rent_per_day: 1000,
    description: "Laid-back cruiser with comfortable seating.",
    details: {
      model_year: 2021,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "Auburn Black",
      seating_capacity: 2,
    },
  },
  {
    id: 14,
    name: "Tvs ntorq 125",
    img: "https://images.app.goo.gl/jZ6V4EfTXrMBVp8X9",
    rent_per_day: 650,
    description: "Sporty scooter with Bluetooth connectivity.",
    details: {
      model_year: 2022,
      fuel_type: "Petrol",
      transmission: "Automatic",
      color: "Metallic Red",
      seating_capacity: 2,
    },
  },
  {
    id: 15,
    name: "Hero XPulse 200",
    img: "https://images.app.goo.gl/v8Nv2qfKa7zfXERr6",
    rent_per_day: 1100,
    description: "Adventure-ready off-road motorcycle.",
    details: {
      model_year: 2023,
      fuel_type: "Petrol",
      transmission: "Manual",
      color: "White",
      seating_capacity: 2,
    },
  },
];
