const destinations = [
  {
    id: 1,
    title: "Gulmarg",
    description: "Famous for skiing and lush meadows.",
    imageUrl: "https://images.app.goo.gl/2cRnBbLkWMjdf4Et7",
    pricePerDayPerAdult: 2500,
    category: "Mountain",
    itinerary: [
      { day: 1, description: "Arrival and check-in." },
      { day: 2, description: "Gondola ride and snow activities." },
    ],
  },
  {
    id: 2,
    title: "Pahalgam",
    description: "A beautiful valley with rivers and pine forests.",
    imageUrl: "https://images.app.goo.gl/Kayda64a84uRdJncA",
    pricePerDayPerAdult: 2400,
    category: "Trekking",
    itinerary: [
      { day: 1, description: "Explore Betaab and Aru Valleys." },
      { day: 2, description: "Trek in the Lidder forest." },
    ],
  },
  {
    id: 3,
    title: "Sonamarg",
    description: "The Meadow of Gold with glacier views.",
    imageUrl: "https://images.app.goo.gl/D3EdbamNj7LPAKMW8",
    pricePerDayPerAdult: 2600,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Visit Thajiwas Glacier." }],
  },
  {
    id: 4,
    title: "Dal Lake",
    description: "Iconic lake with houseboats and shikaras.",
    imageUrl: "https://images.app.goo.gl/Wnbg3jzHtmWDU6js7",
    pricePerDayPerAdult: 2200,
    category: "Lake",
    itinerary: [{ day: 1, description: "Shikara ride and floating market." }],
  },
  {
    id: 5,
    title: "Nigeen Lake",
    description: "A quieter alternative to Dal Lake.",
    imageUrl: "https://images.app.goo.gl/Bvct7TDTh1XwCsvH7",
    pricePerDayPerAdult: 2100,
    category: "Lake",
    itinerary: [{ day: 1, description: "Houseboat stay and sunset cruise." }],
  },
  {
    id: 6,
    title: "Hazratbal Shrine",
    description: "Sacred Muslim site near Dal Lake.",
    imageUrl: "https://images.app.goo.gl/aR7wnwL5CW6Je4RXA",
    pricePerDayPerAdult: 1500,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Shrine visit and lakeside walk." }],
  },
  {
    id: 7,
    title: "Verinag",
    description: "Spring and Mughal garden at Jhelum's origin.",
    imageUrl: "https://images.app.goo.gl/GSDiFX8K7i56VZkw7",
    pricePerDayPerAdult: 1700,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Explore garden and spring." }],
  },
  {
    id: 8,
    title: "Aru Valley",
    description: "Peaceful trekking base near Pahalgam.",
    imageUrl: "https://images.app.goo.gl/49iU1eeGeTWYoY4i7",
    pricePerDayPerAdult: 2300,
    category: "Trekking",
    itinerary: [{ day: 1, description: "Nature trail and camping." }],
  },
  {
    id: 9,
    title: "Betaab Valley",
    description: "Scenic valley named after Bollywood film.",
    imageUrl: "https://images.app.goo.gl/pYaMMsscJBUHRBPT7",
    pricePerDayPerAdult: 2000,
    category: "Trekking",
    itinerary: [{ day: 1, description: "Photography and picnic." }],
  },
  {
    id: 10,
    title: "Yusmarg",
    description: "Calm hill station with pine trees.",
    imageUrl: "https://images.app.goo.gl/Srm7ntW1vwQVr7fE8",
    pricePerDayPerAdult: 2100,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Horse riding and trails." }],
  },
  {
    id: 11,
    title: "Lolab Valley",
    description: "Underrated beauty in north Kashmir.",
    imageUrl: "https://images.app.goo.gl/EUCg4xpEWgYcafZG9",
    pricePerDayPerAdult: 2000,
    category: "Trekking",
    itinerary: [{ day: 1, description: "Hike to lush forests." }],
  },
  {
    id: 12,
    title: "Bangus Valley",
    description: "Remote valley with grasslands and rivers.",
    imageUrl: "https://images.app.goo.gl/MKTMXKB7mZZL5dpp7",
    pricePerDayPerAdult: 2500,
    category: "Trekking",
    itinerary: [{ day: 1, description: "Explore valley on foot or horse." }],
  },
  {
    id: 13,
    title: "Shankaracharya Temple",
    description: "Ancient temple with panoramic Srinagar view.",
    imageUrl: "https://images.app.goo.gl/v4KWLBJREkpTaY5A8",
    pricePerDayPerAdult: 1800,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Morning temple trek and view." }],
  },
  {
    id: 14,
    title: "Char Chinar",
    description: "Island with 4 chinar trees in Dal Lake.",
    imageUrl: "https://images.app.goo.gl/kzv7orsz1WvXiSH96",
    pricePerDayPerAdult: 1600,
    category: "Lake",
    itinerary: [{ day: 1, description: "Shikara to Char Chinar island." }],
  },
  {
    id: 15,
    title: "Wular Lake",
    description: "Largest freshwater lake in India.",
    imageUrl: "https://example.com/images/wular.jpg",
    pricePerDayPerAdult: 1900,
    category: "Lake",
    itinerary: [{ day: 1, description: "Birdwatching and boat ride." }],
  },
  {
    id: 16,
    title: "Achabal Gardens",
    description: "Mughal garden with cascading waters.",
    imageUrl: "https://images.app.goo.gl/bXUpTnqM5vxFyjtW9",
    pricePerDayPerAdult: 1800,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Walk in gardens and fountains." }],
  },
  {
    id: 17,
    title: "Martand Sun Temple",
    description: "Ancient Hindu ruins near Anantnag.",
    imageUrl: "https://images.app.goo.gl/VRoFfVoEiWMJawV28",
    pricePerDayPerAdult: 1700,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Visit ruins and nearby market." }],
  },
  {
    id: 18,
    title: "Gurez Valley",
    description: "Remote border valley with stunning views.",
    imageUrl: "https://images.app.goo.gl/zbwepgVkb4Hym8wA8",
    pricePerDayPerAdult: 2700,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Drive through Razdan Pass." }],
  },
  {
    id: 19,
    title: "Manasbal Lake",
    description: "Known for lotus blooms and birdlife.",
    imageUrl: "https://images.app.goo.gl/gmTs472BX9RKw5Gr8",
    pricePerDayPerAdult: 1900,
    category: "Lake",
    itinerary: [{ day: 1, description: "Lotus viewing and boating." }],
  },
  {
    id: 20,
    title: "Kokernag",
    description: "Spring with medicinal value and gardens.",
    imageUrl: "https://images.app.goo.gl/7GL1zFEdEcfcoeJA8",
    pricePerDayPerAdult: 1800,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Taste spring water and walk." }],
  },
  {
    id: 21,
    title: "Sinthan Top",
    description: "High mountain pass with 360° views.",
    imageUrl: "https://images.app.goo.gl/hPBEoxeHQu2rZKD67",
    pricePerDayPerAdult: 2500,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Drive and photography." }],
  },
  {
    id: 22,
    title: "Tulip Garden",
    description: "Asia’s largest tulip garden in spring.",
    imageUrl: "https://images.app.goo.gl/VCFDU6eBPH9A55L47",
    pricePerDayPerAdult: 2000,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Walk among blooming tulips." }],
  },
  {
    id: 23,
    title: "Mughal Road",
    description: "Historic scenic road connecting Kashmir with Poonch.",
    imageUrl: "https://images.app.goo.gl/BpXzmKQgivwM52h78",
    pricePerDayPerAdult: 2200,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Drive and explore Pir Panjal views." }],
  },
  {
    id: 24,
    title: "Pari Mahal",
    description: "Historic garden with Persian-style architecture.",
    imageUrl:
      "https://assets.cntraveller.in/photos/61eff70d4d495b4b023dc466/16:9/w_1024%2Cc_limit/parimahal%2520lead.jpg",
    pricePerDayPerAdult: 1800,
    category: "Historical Place",
    itinerary: [{ day: 1, description: "Sunset view from garden terrace." }],
  },
  {
    id: 25,
    title: "Doodhpathri",
    description: "Green meadows and grazing lands with streams.",
    imageUrl:
      "https://gulmargriders.com/wp-content/uploads/2020/11/Doodhpathri.jpg",
    pricePerDayPerAdult: 2300,
    category: "Mountain",
    itinerary: [{ day: 1, description: "Picnic, nature walks, horse ride." }],
  },
];
