
const campingGearItems = [
  {
    id: 1,
    name: "Alpine 2-Person Tent",
    description: "Lightweight and weatherproof tent suitable for all seasons.",
    category: "Tent",
    price: 8500,
    brand: "Wildcraft",
    features: ["Waterproof", "Easy setup", "Wind resistant"],
    image: './images/campingimages/img1.jpg',
  },
  {
    id: 2,
    name: "Thermal Sleeping Bag",
    description: "Cold weather sleeping bag with mummy-style insulation.",
    category: "Sleeping Bag",
    price: 3200,
    brand: "Quechua",
    features: ["-10°C rating", "Compact", "Synthetic filling"],
    image: "https://images.app.goo.gl/VyHGXyRHcfA36nfD8",
  },
  {
    id: 3,
    name: "Portable Gas Stove",
    description: "Compact gas stove perfect for trekking and camping.",
    category: "Stove",
    price: 1800,
    brand: "Coleman",
    features: ["Fuel-efficient", "Foldable", "Piezo ignition"],
    image: "https://images.app.goo.gl/M1WGmtFM1a9adVwT9",
  },
  {
    id: 4,
    name: "65L Trekking Backpack",
    description: "Ergonomic backpack with adjustable straps and rain cover.",
    category: "Backpack",
    price: 4200,
    brand: "Decathlon",
    features: ["Hydration pouch", "Multiple compartments", "Rainproof"],
    image: "https://g.co/kgs/37fLj1m",
  },
  {
    id: 5,
    name: "LED Camping Lantern",
    description: "Bright LED lantern with USB charging capability.",
    category: "Lighting",
    price: 1200,
    brand: "Fenix",
    features: ["Rechargeable", "Hanging hook", "4 brightness levels"],
    image: "https://images.app.goo.gl/m6Q58Tqpr7R2919j7",
  },
  {
    id: 6,
    name: "Inflatable Camping Mattress",
    description: "Self-inflating mattress for comfortable sleep outdoors.",
    category: "Furniture",
    price: 2600,
    brand: "Naturehike",
    features: ["Lightweight", "Compact", "Water-resistant bottom"],
    image: "https://images.app.goo.gl/vuWRrXPzThS3dE5y7",
  },
  {
    id: 7,
    name: "Aluminum Trekking Poles",
    description: "Adjustable trekking poles with anti-shock mechanism.",
    category: "Trekking Gear",
    price: 1400,
    brand: "Black Diamond",
    features: ["Height adjustable", "Foam grip", "Anti-shock tips"],
    image: "https://images.app.goo.gl/2x7Ua4a2XcPM3rNdA",
  },
  {
    id: 8,
    name: "Camping Chair",
    description: "Folding chair with back support and cup holder.",
    category: "Furniture",
    price: 1900,
    brand: "REI",
    features: ["Folds flat", "Cup holder", "Steel frame"],
    image: "https://images.app.goo.gl/Grm6RL7DetQoZC5dA",
  },
  {
    id: 9,
    name: "Compact Water Filter",
    description: "Portable water filter ideal for mountain streams.",
    category: "Water Gear",
    price: 2300,
    brand: "LifeStraw",
    features: ["Removes 99.9% bacteria", "No chemicals", "Portable"],
    image: "https://images.app.goo.gl/egdsWmyQvoa7S7Sq9",
  },
  {
    id: 10,
    name: "LED Headlamp",
    description: "Hands-free light source with adjustable brightness.",
    category: "Lighting",
    price: 800,
    brand: "Petzl",
    features: ["Rechargeable", "Tilt angle", "Water-resistant"],
    image: "https://g.co/kgs/Y91cT4V",
  },
  {
    id: 11,
    name: "Ultralight Sleeping Pad",
    description: "Compact and lightweight foam pad for sleeping comfort.",
    category: "Furniture",
    price: 1600,
    brand: "Therm-a-Rest",
    features: ["Foam-based", "Compact", "Durable"],
    image: "https://images.app.goo.gl/gGM6uWXMPpgnebQr6",
  },
  {
    id: 12,
    name: "Trekking Shoes",
    description: "Durable trekking shoes with anti-slip sole.",
    category: "Footwear",
    price: 4600,
    brand: "Salomon",
    features: ["Waterproof", "Breathable", "Anti-slip sole"],
    image: "https://g.co/kgs/TfXs74f",
  },
  {
    id: 13,
    name: "Windproof Jacket",
    description: "Layered jacket suitable for high-altitude trekking.",
    category: "Trekking Gear",
    price: 3500,
    brand: "North Face",
    features: ["Windproof", "Thermal lining", "Packable"],
    image: "https://images.app.goo.gl/ZknH1mp8kDXbjdDi6",
  },
  {
    id: 14,
    name: "Tent Footprint",
    description: "Ground cover to protect your tent base.",
    category: "Tent",
    price: 900,
    brand: "MSR",
    features: ["Tear-resistant", "Waterproof", "Lightweight"],
    image: "https://images.app.goo.gl/Dcf63odqbGCK5sxq9",
  },
  {
    id: 15,
    name: "Foldable Camp Table",
    description: "Compact table for meals and activities outdoors.",
    category: "Furniture",
    price: 2800,
    brand: "Alps Mountaineering",
    features: ["Light aluminum", "Foldable", "Portable case"],
    image: "https://g.co/kgs/TGJZqCF",
  },
  {
    id: 16,
    name: "Rechargeable Torch",
    description: "High-lumen flashlight for camping and trekking.",
    category: "Lighting",
    price: 1000,
    brand: "Olight",
    features: ["USB charging", "High beam", "Waterproof"],
    image: "https://g.co/kgs/ojmvAHC",
  },
  {
    id: 17,
    name: "Fire Starter Kit",
    description: "All-weather fire starter for emergency use.",
    category: "Trekking Gear",
    price: 700,
    brand: "UST",
    features: ["Waterproof", "Works when wet", "Compact"],
    image: "https://g.co/kgs/BXARyGd",
  },
  {
    id: 18,
    name: "Dry Bag Set",
    description: "Keeps your gear dry in rainy and wet conditions.",
    category: "Water Gear",
    price: 1500,
    brand: "Sea to Summit",
    features: ["Multiple sizes", "Roll-top closure", "Durable"],
    image: "https://images.app.goo.gl/ySYvuwC2tzLVBQFp8",
  },
  {
    id: 19,
    name: "Multi-tool Knife",
    description: "Multipurpose knife with tools for any outdoor task.",
    category: "Trekking Gear",
    price: 2100,
    brand: "Victorinox",
    features: ["Blade, scissors, saw", "Compact", "Stainless steel"],
    image: "https://g.co/kgs/dscnV2f",
  },
  {
    id: 20,
    name: "Solar Camping Shower",
    description: "Portable solar-powered shower bag.",
    category: "Water Gear",
    price: 1800,
    brand: "Advanced Elements",
    features: ["5-gallon capacity", "Heats water using sunlight", "Foldable"],
    image: "https://images.app.goo.gl/rUZuJhMDQsR3U6H1A",
  },
  {
    id: 21,
    name: "Camping Kettle",
    description: "Aluminum kettle for boiling water on the go.",
    category: "Stove",
    price: 1300,
    brand: "Fire Maple",
    features: ["Lightweight", "Quick heating", "Compact"],
    image: "https://images.app.goo.gl/aWbmuo1E8wXDJYk88",
  },
  {
    id: 22,
    name: "Grip Trekking Gloves",
    description: "Insulated gloves with excellent grip for trekking.",
    category: "Trekking Gear",
    price: 1100,
    brand: "Forclaz",
    features: ["Windproof", "Touchscreen friendly", "Anti-slip palms"],
    image: "https://images.app.goo.gl/UFL2fi7zy9pfaEU38",
  },
];
